# add the following to _config.yml file
title: Emily Godson née Wheaton
description: **TechWomen100 Winner 2023** Recipient of the prestigious TechWomen100 Individual award in 2023, recognized by WeAreTechWomen for outstanding contributions to the field of technology, showcasing excellence and leadership in the industry
logo: Screenshot 2024-07-23 at 16.39.28.png
theme: jekyll-theme-minimal
